"""inclui relacionamento entre sala e item

Revision ID: 5ffd5019db5e
Revises: 67c3bdfc911a
Create Date: 2018-07-09 12:38:41.491934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffd5019db5e'
down_revision = '67c3bdfc911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.add_column(u'item', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column(u'item', 'room_id')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###
